setup apache webserver using terraform provisioner

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,76 +1,76 @@
-name: "Terraform"
+# name: "Terraform"
 
-on:
-  push:
-    branches:
-      - master
-  pull_request:
+# on:
+#   push:
+#     branches:
+#       - master
+#   pull_request:
 
-jobs:
-  terraform:
-    name: "Terraform"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout  #check out the current configuration
-        uses: actions/checkout@v2 #the '/checkout@v2' is the docker image to run
+# jobs:
+#   terraform:
+#     name: "Terraform"
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout  #check out the current configuration
+#         uses: actions/checkout@v2 #the '/checkout@v2' is the docker image to run
 
-      - name: Setup Terraform #this step retrieves the terra cli used in d github action workflow. the cli will defaults to the latest stable version
-      # you can modify the version though using the terra version attr. this step will also load d TF_API_TOKEN secret
-        uses: hashicorp/setup-terraform@v1 #the image to run
-        with:
-          # terraform_version: 0.13.0:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#       - name: Setup Terraform #this step retrieves the terra cli used in d github action workflow. the cli will defaults to the latest stable version
+#       # you can modify the version though using the terra version attr. this step will also load d TF_API_TOKEN secret
+#         uses: hashicorp/setup-terraform@v1 #the image to run
+#         with:
+#           # terraform_version: 0.13.0:
+#           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      - name: Terraform Format #ensures the config is properly configured and enforces terra best practices
-        id: fmt
-        run: terraform fmt -check
+#       - name: Terraform Format #ensures the config is properly configured and enforces terra best practices
+#         id: fmt
+#         run: terraform fmt -check
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
+#       - name: Terraform Init
+#         id: init
+#         run: terraform init
       
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+#       - name: Terraform Validate
+#         id: validate
+#         run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request' #this step shld only run on pull request
-        run: terraform plan -no-color
-        continue-on-error: true #step will continue even if an error occurs
+#       - name: Terraform Plan
+#         id: plan
+#         if: github.event_name == 'pull_request' #this step shld only run on pull request
+#         run: terraform plan -no-color
+#         continue-on-error: true #step will continue even if an error occurs
 
-      - uses: actions/github-script@0.9.0
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#       - uses: actions/github-script@0.9.0
+#         if: github.event_name == 'pull_request'
+#         env:
+#           PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
+#           script: |
+#             const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#             #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#             #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#             #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
-            <details><summary>Show Plan</summary>
+#             <details><summary>Show Plan</summary>
 
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
+#             \`\`\`\n
+#             ${process.env.PLAN}
+#             \`\`\`
 
-            </details>
+#             </details>
 
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.issues.createComment({ 
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+#             *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#             github.issues.createComment({ 
+#               issue_number: context.issue.number,
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               body: output
+#             })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-        run: terraform apply -auto-approve
+#       - name: Terraform Apply
+#         if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+#         run: terraform apply -auto-approve
